/*This file prepares the database by copying tables from menumine and menumine_admin to menumine_backup and menumine_admin_backup.
 * databaseprep2.sql is an almost identical script which copies the backup databases to the databaseprep databases.
 */
DROP TABLE IF EXISTS `menumine_backup`.`tblchain`;
 CREATE  TABLE  `menumine_backup`.`tblchain` (  `ID` int( 10  )  NOT  NULL  auto_increment ,
 `1` double( 15, 5  )  default NULL ,
 `Chain` varchar( 255  )  default NULL  COMMENT  'changed to 255 characters Oct 7 2009',
 `SectorName` varchar( 50  )  default NULL ,
 `Segment` varchar( 50  )  default NULL ,
 `HQAddress` varchar( 50  )  default NULL ,
 `HQCity` varchar( 50  )  default NULL ,
 `HQState` varchar( 50  )  default NULL ,
 `OperatorType` varchar( 50  )  default NULL ,
 `HQRegion` varchar( 50  )  default NULL ,
 `HQZip` varchar( 50  )  default NULL ,
 `Phone` varchar( 50  )  default NULL ,
 `Fax` varchar( 50  )  default NULL ,
 `WebSite` varchar( 50  )  default NULL ,
 `Units2009` int( 10  )  default NULL ,
 `Sales2009` decimal( 19, 4  )  default NULL ,
 `IndusRankDoll-09` varchar( 50  )  default NULL ,
 `IndusRankUnits-09` varchar( 50  )  default NULL ,
 `SegRnkDoll-09a` varchar( 50  )  default NULL ,
 `SegRankUnits-09` varchar( 50  )  default NULL ,
 `MenuInHouseMonth-09` varchar( 50  )  default NULL ,
 `Units2008` int( 10  )  default NULL ,
 `Units2007` int( 10  )  default NULL ,
 `Units2006` int( 10  )  default NULL ,
 `Units2005` int( 10  )  default NULL ,
 `Units2004` int( 10  )  default NULL ,
 `Units2003` int( 10  )  default NULL ,
 `Sales2008` double  default NULL ,
 `Sales2007` double  default NULL ,
 `Sales2006` double  default NULL ,
 `Sales2005` double  default NULL ,
 `Sales2004` double  default NULL ,
 `Sales2003` double  default NULL ,
 `ParentCo` varchar( 50  )  default NULL ,
 `ParentAddress` varchar( 50  )  default NULL ,
 `ParentCity` varchar( 50  )  default NULL ,
 `ParentState` varchar( 50  )  default NULL ,
 `ParentZip` int( 10  )  default NULL ,
 `NatRegLocal` varchar( 50  )  default NULL ,
 `PerStoreAver` decimal( 19, 4  )  default NULL ,
 `MAP-Chains` varchar( 50  )  default NULL ,
 `CountryLoc` varchar( 50  )  default NULL ,
 `FirstYearInDatabase` int( 10  )  default NULL ,
 `IndusRankDoll-08` varchar( 50  )  default NULL ,
 `IndusRankDoll-07` varchar( 50  )  default NULL ,
 `IndusRankUnits-08` varchar( 50  )  default NULL ,
 `IndusRankUnits-07` varchar( 50  )  default NULL ,
 `SegRankDoll-08` varchar( 50  )  default NULL ,
 `SegRankDoll-07` varchar( 50  )  default NULL ,
 `SegRankUnits-08` varchar( 50  )  default NULL ,
 `SegRankUnits-07` varchar( 50  )  default NULL ,
 `IndusRankDoll-06` varchar( 50  )  default NULL ,
 `IndusRankDoll-05` varchar( 50  )  default NULL ,
 `IndusRankDoll-04` varchar( 50  )  default NULL ,
 `IndusRankDoll-03` varchar( 50  )  default NULL ,
 `IndusRankUnits-06` varchar( 50  )  default NULL ,
 `IndusRankUnits-05` varchar( 50  )  default NULL ,
 `IndusRankUnits-04` varchar( 50  )  default NULL ,
 `IndusRankUnits-03` varchar( 50  )  default NULL ,
 `SegRankDoll-06` varchar( 50  )  default NULL ,
 `SegRankDoll-05` varchar( 50  )  default NULL ,
 `SegRankDoll-04` varchar( 50  )  default NULL ,
 `SegRankDoll-03` varchar( 50  )  default NULL ,
 `SegRankUnits-06` varchar( 50  )  default NULL ,
 `SegRankUnits-05` varchar( 50  )  default NULL ,
 `SegRankUnits-04` varchar( 50  )  default NULL ,
 `SegRankUnits-03` varchar( 50  )  default NULL ,
 `FoodBeatTop200` varchar( 50  )  default NULL ,
 `MenuMineNRNTops` varchar( 50  )  default NULL ,
 `TopsRank` varchar( 50  )  default NULL ,
 `NewItemWhen` datetime  default NULL ,
 `ChainLogo` varchar( 50  )  default NULL ,
 `NoteOne` varchar( 50  )  default NULL ,
 `ZagatFoodRate2006` int( 10  )  default NULL ,
 `ZagatFoodRate1997` int( 10  )  default NULL ,
 `ZagatCheckSize2006` decimal( 19, 4  )  default NULL ,
 `PickUpAreaAddress` varchar( 85  )  default NULL ,
 `PickupAreaCity` varchar( 50  )  default NULL ,
 `PickUpAreaMetro` varchar( 50  )  default NULL ,
 `MenuCollectState` varchar( 50  )  default NULL  COMMENT  'Used to be PickUpAreaState',
 `PickUpAreaPhone` varchar( 50  )  default NULL ,
 `PickUpAreaZip` varchar( 50  )  default NULL ,
 `ChicagoPickUpZone` varchar( 50  )  default NULL ,
 `MenuCollectBy` varchar( 50  )  default NULL ,
 `MenuInHouseMonth-06` varchar( 50  )  default NULL ,
 `MenuInHouseMonth-07` varchar( 50  )  default NULL ,
 `MenuInHouseMonth-08` varchar( 50  )  default NULL ,
 `MenuCollectCycle` varchar( 50  )  default NULL ,
 `MenuCollectMonth` varchar( 50  )  default NULL ,
 `DataEntryMonth` varchar( 50  )  default NULL ,
 `ProdUser` varchar( 10  )  default NULL  COMMENT  'Name of person who completes menu',
 `ProdTime` int( 3  )  default NULL  COMMENT  'The amount of time it takes to complete a menu',
 `ProdDate` date  default NULL  COMMENT  'The Date the menu was completed on',
 `Segment-RiMag` varchar( 50  )  default NULL ,
 `MenuCollectRegion` varchar( 50  )  default NULL  COMMENT  'Used to be PickUpRegion',
 `RiMagUnits` int( 10  )  default NULL ,
 `RiMagUnitRank` int( 10  )  default NULL ,
 `RiMagSalesVol` decimal( 19, 4  )  default NULL ,
 `RiMagSalesRank` int( 10  )  default NULL ,
 `RiMagSegRank` int( 10  )  default NULL ,
 `NoteTwo` varchar( 100  )  default NULL ,
 `UpdatedTo2006` varchar( 50  )  default NULL ,
 `CompetitiveDB` varchar( 50  )  default NULL ,
 `DBinsights-mktseg` varchar( 50  )  default NULL ,
 `DBmonitor` varchar( 50  )  default NULL ,
 `Serves Breakfast` varchar( 50  )  default NULL ,
 `UnitsUniverseSegment` int( 10  )  default NULL ,
 `ChainSize` varchar( 15  )  default NULL ,
 PRIMARY  KEY (  `ID`  ) ,
 KEY  `chain_chainid` (  `1`  )  ) ENGINE  = InnoDB  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_backup`.`tblchain` SELECT * FROM `menumine`.`tblchain`;
DROP TABLE IF EXISTS `menumine_backup`.`tblmasterfood`;
 CREATE  TABLE  `menumine_backup`.`tblmasterfood` (  `ID` int( 10  )  NOT  NULL  auto_increment ,
 `MenuStatus` varchar( 255  )  default NULL ,
 `DayPartCategory` varchar( 50  )  default NULL ,
 `Chain` varchar( 255  )  default NULL ,
 `ChainID` int( 10  )  default NULL ,
 `CountryLoc` varchar( 50  )  default NULL ,
 `OperatorType` varchar( 50  )  default NULL ,
 `HQRegion` varchar( 50  )  default NULL ,
 `HQState` varchar( 50  )  default NULL ,
 `YearPutInDatabase` int( 10  )  default NULL ,
 `OperationName` varchar( 50  )  default NULL ,
 `SectorName` varchar( 50  )  default NULL ,
 `MenuItem` varchar( 255  )  default NULL ,
 `BevMenuItem` varchar( 50  )  default NULL ,
 `MenuItemType` varchar( 255  )  default NULL ,
 `GenMenuPart` varchar( 50  )  default NULL ,
 `Menu Item Class` varchar( 50  )  default NULL ,
 `MenuItemClassOld` varchar( 50  )  default NULL  COMMENT  'Used to be called ''Menu Item Class''',
 `SectionTerm` varchar( 50  )  default NULL ,
 `MenuType` varchar( 255  )  default NULL ,
 `ItemDescription` longtext,
 `TasteFlavorWords` varchar( 50  )  default NULL ,
 `ChickenType` varchar( 50  )  default NULL ,
 `BeefType` varchar( 50  )  default NULL ,
 `PorkType` varchar( 50  )  default NULL ,
 `FishType` varchar( 50  )  default NULL ,
 `SeafoodType` varchar( 50  )  default NULL ,
 `LambType` varchar( 50  )  default NULL ,
 `TurkeyType` varchar( 50  )  default NULL ,
 `OtherProteinType` varchar( 50  )  default NULL ,
 `ShrimpType` varchar( 50  )  default NULL ,
 `Protein Type/Cut` varchar( 50  )  default NULL ,
 `BasicProtein` varchar( 50  )  default NULL ,
 `Finfish Species` varchar( 50  )  default NULL ,
 `ProteinApp` varchar( 50  )  default NULL  COMMENT  'how is the protein used',
 `ProteinTopName` varchar( 50  )  default NULL ,
 `ProteinAccompName` varchar( 50  )  default NULL ,
 `CookMeth` varchar( 50  )  default NULL ,
 `GenCookMeth` varchar( 50  )  default NULL ,
 `Cuisine` varchar( 50  )  default NULL ,
 `Cuisine, Family` varchar( 50  )  default NULL ,
 `Marinade` varchar( 50  )  default NULL ,
 `Glaze` varchar( 50  )  default NULL ,
 `Cooking Sauce or Gravy` varchar( 50  )  default NULL ,
 `Condiments` varchar( 50  )  default NULL ,
 `Dressings` varchar( 50  )  default NULL ,
 `DipSauceName` varchar( 50  )  default NULL ,
 `SeasoningName` varchar( 50  )  default NULL ,
 `Stuff Name` varchar( 50  )  default NULL ,
 `Batter/Breading/Coating` varchar( 50  )  default NULL ,
 `ButterApplication` varchar( 50  )  default NULL ,
 `DairyButterCream` varchar( 50  )  default NULL ,
 `VeggieFruitType` varchar( 100  )  default NULL ,
 `GreenVegName` varchar( 50  )  default NULL ,
 `VegTopName` varchar( 50  )  default NULL ,
 `VeggieAll` varchar( 50  )  default NULL ,
 `VegAccompName` varchar( 50  )  default NULL ,
 `TomatoType` varchar( 50  )  default NULL ,
 `OnionScallionLeek` varchar( 50  )  default NULL ,
 `MushroomType` varchar( 50  )  default NULL ,
 `OtherAccompaniments` varchar( 50  )  default NULL ,
 `OtherToppings` varchar( 50  )  default NULL ,
 `OtherIngredName` varchar( 50  )  default NULL ,
 `CarboType` varchar( 50  )  default NULL ,
 `CarboAccompName` varchar( 50  )  default NULL ,
 `CarboAccompOrType` varchar( 50  )  default NULL ,
 `CarboAll` varchar( 50  )  default NULL ,
 `CarboTopName` varchar( 50  )  default NULL ,
 `BreadUse` varchar( 50  )  default NULL ,
 `Bread/Wrap/Chips` varchar( 50  )  default NULL ,
 `BreakfastPastry` varchar( 50  )  default NULL ,
 `Cheese` varchar( 50  )  default NULL ,
 `CheeseRollUp` varchar( 50  )  default NULL ,
 `Cheese Form` varchar( 50  )  default NULL ,
 `Cheese/CheeseSauceFillingType` varchar( 50  )  default NULL ,
 `CreamCheeseorCottageCheese` varchar( 50  )  default NULL ,
 `SoupBaseBroth` varchar( 50  )  default NULL ,
 `SoupWith` varchar( 50  )  default NULL ,
 `Side/AccompDishFlavor` varchar( 50  )  default NULL ,
 `SideOrAccomp` varchar( 50  )  default NULL ,
 `AnyFruit` varchar( 50  )  default NULL ,
 `HealthyTerm` varchar( 50  )  default NULL ,
 `HealthyFlag` varchar( 50  )  default NULL ,
 `HealthySymbol` varchar( 50  )  default NULL ,
 `CurrentPrice` decimal( 19, 4  )  default NULL ,
 `'96 Price` double  default NULL ,
 `'97 Price` double  default NULL ,
 `'98 Price` double  default NULL ,
 `'99 Price` double  default NULL ,
 `2000 Price` double  default NULL ,
 `2001 Price` double  default NULL ,
 `2002 Price` double  default NULL ,
 `2003 Price` double  default NULL ,
 `2004 Price` double  default NULL ,
 `2005 Price` double  default NULL ,
 `2006 Price` double  default NULL ,
 `2007 Price` double  default NULL ,
 `2008 Price` double  default NULL ,
 `2009 Price` double  default NULL ,
 `2010 Price` double  default NULL ,
 `2011 Price` double  default NULL ,
 `2010_temp` decimal( 19, 4  )  default NULL ,
 `Serving Size` varchar( 50  )  default NULL ,
 `ServingCount` varchar( 50  )  default NULL ,
 `AppetizerorSide` varchar( 50  )  default NULL ,
 `MealService` varchar( 50  )  default NULL ,
 `Egg Count` varchar( 50  )  default NULL ,
 `Egg Type` varchar( 50  )  default NULL ,
 `Fruit Type` varchar( 50  )  default NULL ,
 `Syrup/Topping` varchar( 50  )  default NULL ,
 `Spread Type` varchar( 50  )  default NULL ,
 `Hot/Cold Cereal` varchar( 50  )  default NULL ,
 `BevSize` varchar( 50  )  default NULL ,
 `BevTopSyrup` varchar( 50  )  default NULL ,
 `BreakCakeWaff` varchar( 50  )  default NULL ,
 `LogoImageStyle` varchar( 50  )  default NULL ,
 `NutIngredient` varchar( 50  )  default NULL ,
 `DessertDoughCrustIngred` varchar( 50  )  default NULL ,
 `CakeIngredient` varchar( 50  )  default NULL ,
 `CakeUse` varchar( 50  )  default NULL ,
 `CookieUse` varchar( 50  )  default NULL ,
 `CookieIngredient` varchar( 50  )  default NULL ,
 `CookieType_Source` varchar( 50  )  default NULL ,
 `CookieorNutIngredient` varchar( 50  )  default NULL ,
 `FruitorFruitFillingIngred` varchar( 50  )  default NULL ,
 `IceCreamIngredient` varchar( 50  )  default NULL ,
 `WhippedToppingIngred` varchar( 50  )  default NULL ,
 `CreamyTop` varchar( 50  )  default NULL ,
 `CreamyFill` varchar( 50  )  default NULL ,
 `CandyIngredient` varchar( 50  )  default NULL ,
 `Station` varchar( 50  )  default NULL ,
 `PrimaryFlavor` varchar( 50  )  default NULL ,
 `Brand` varchar( 50  )  default NULL ,
 `OtherTop/Ingred` varchar( 50  )  default NULL ,
 `AccompSideIngredMM` varchar( 50  )  default NULL ,
 `SauceCondDressMarMM` varchar( 255  )  default NULL ,
 `FlavEnhancSeasBrdgDesIngredMM` varchar( 50  )  default NULL ,
 `Top/Fill/IngredMM` varchar( 50  )  default NULL ,
 `BreadBakeGoodsMM` varchar( 50  )  default NULL ,
 `FlavorSoup` varchar( 50  )  default NULL ,
 `FlavApplication` varchar( 50  )  default NULL ,
 `CuisineVerySpecific` varchar( 50  )  default NULL ,
 `GrillRoastSmoke` varchar( 50  )  default NULL ,
 `VegCookMeth` varchar( 50  )  default NULL ,
 `CookSauceType` varchar( 50  )  default NULL ,
 `DressingType` varchar( 50  )  default NULL ,
 `DressingFlavor` varchar( 50  )  default NULL ,
 `MexBreadType` varchar( 50  )  default NULL ,
 `RoastVegItemType` varchar( 50  )  default NULL ,
 `AppetClassTyp` varchar( 50  )  default NULL ,
 `PrepEntreeType` varchar( 50  )  default NULL ,
 `DeepFriedSauteedItemTypes` varchar( 50  )  default NULL  COMMENT  'Changed from BreadedFriedAppSide',
 `PotatoTypeUse` varchar( 50  )  default NULL ,
 `SalsaType` varchar( 50  )  default NULL ,
 `CookieLookAlikeDessert` varchar( 50  )  default NULL ,
 `BreakfastToGo` varchar( 50  )  default NULL ,
 `PizzaStyle` varchar( 50  )  default NULL ,
 `BBQCook` varchar( 50  )  default NULL ,
 `EthnicBreadType` varchar( 50  )  default NULL ,
 `PepperType` varchar( 50  )  default NULL ,
 `RiceTypeUse` varchar( 50  )  default NULL ,
 `MexIngredUse` varchar( 50  )  default NULL ,
 `NewItemBrag` varchar( 50  )  default NULL ,
 `ProteinFlavorApp` varchar( 50  )  default NULL ,
 `OilTypeUse` varchar( 50  )  default NULL ,
 `EggItemUse` varchar( 50  )  default NULL ,
 `AllVegCarbFruit` varchar( 50  )  default NULL ,
 `TextureAttrib` varchar( 50  )  default NULL ,
 `QualityStyle` varchar( 50  )  default NULL ,
 `CrossoverFlag` varchar( 3  )  NOT  NULL default  'NO',
 `CrossoverIngred` varchar( 75  )  default NULL ,
 `CrossoverType` varchar( 50  )  default NULL ,
 `Segment` varchar( 255  )  default NULL ,
 `CrossMainEthnic` varchar( 30  )  default NULL ,
 `TIMESTAMP` timestamp NOT  NULL  default CURRENT_TIMESTAMP  on  update  CURRENT_TIMESTAMP ,
 `modifiedBy` varchar( 10  )  default NULL ,
 `Notes` text,
 `Flag` tinyint( 1  )  NOT  NULL default  '0',
 `ProteinType` varchar( 50  )  default NULL ,
 `VeggieFruitMM` varchar( 50  )  default NULL ,
 `CarboMM` varchar( 50  )  default NULL ,
 `keywords` text,
 `FillingSauces/Dressings` varchar( 50  )  default NULL ,
 `BreadedFriedAppSide` varchar( 50  )  default NULL ,
 `FlavorChangeAnyYear` varchar( 255  )  default NULL ,
 `CookieType/Source` varchar( 50  )  default NULL ,
 PRIMARY  KEY (  `ID`  ) ,
 KEY  `mf_chainid` (  `ChainID`  ) ,
 KEY  `mf_daypartcategory` (  `DayPartCategory`  ) ,
 KEY  `mf_hqregion` (  `HQRegion`  ) ,
 KEY  `mf_marketsegment` (  `Segment`  ) ,
 KEY  `mf_marketsector` (  `SectorName`  ) ,
 KEY  `mf_menupart` (  `GenMenuPart`  ) ,
 KEY  `mf_basicprotein` (  `BasicProtein`  ) ,
 KEY  `mf_cuisineofitem` (  `Cuisine`  ) ,
 KEY  `mf_cookingmethod` (  `CookMeth`  ) ,
 KEY  `mf_operationname` (  `OperationName`  ) ,
 KEY  `mf_cuisinefamily` (  `Cuisine, Family`  ) ,
 KEY  `mf_gencookingmethod` (  `GenCookMeth`  ) ,
 KEY  `mf_menuitemclass` (  `Menu Item Class`  ) ,
 KEY  `mf_menustatus` (  `MenuStatus`  ) ,
 KEY  `mf_cakeuse` (  `CakeUse`  ) ,
 KEY  `mf_cookieuse` (  `CookieUse`  ) ,
 KEY  `mf_proteintypecut` (  `Protein Type/Cut`  ) ,
 KEY  `mf_proteintype` (  `ProteinType`  ) ,
 KEY  `mf_finfishspecies` (  `Finfish Species`  ) ,
 KEY  `mf_newitembrag` (  `NewItemBrag`  ) ,
 KEY  `mf_proteinflavorapp` (  `ProteinFlavorApp`  ) ,
 FULLTEXT  KEY  `mf_keywords` (  `keywords`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_backup`.`tblmasterfood` SELECT * FROM `menumine`.`tblmasterfood`;
DROP TABLE IF EXISTS `menumine_backup`.`tblstatelocation`;
 CREATE  TABLE  `menumine_backup`.`tblstatelocation` (  `ID1` int( 10  )  NOT  NULL  auto_increment ,
 `IDnumber` double( 15, 5  )  default NULL ,
 `1` double( 15, 5  )  default NULL ,
 `Chain` varchar( 255  )  default NULL ,
 `AK` double( 15, 5  )  default NULL ,
 `AL` double( 15, 5  )  default NULL ,
 `AR` double( 15, 5  )  default NULL ,
 `AZ` double( 15, 5  )  default NULL ,
 `CA` double( 15, 5  )  default NULL ,
 `CO` double( 15, 5  )  default NULL ,
 `CT` double( 15, 5  )  default NULL ,
 `DC` double( 15, 5  )  default NULL ,
 `DE` double( 15, 5  )  default NULL ,
 `FL` double( 15, 5  )  default NULL ,
 `GA` double( 15, 5  )  default NULL ,
 `HI` double( 15, 5  )  default NULL ,
 `IA` double( 15, 5  )  default NULL ,
 `ID` double( 15, 5  )  default NULL ,
 `IL` double( 15, 5  )  default NULL ,
 `IN` double( 15, 5  )  default NULL ,
 `KS` double( 15, 5  )  default NULL ,
 `KY` double( 15, 5  )  default NULL ,
 `LA` double( 15, 5  )  default NULL ,
 `MA` double( 15, 5  )  default NULL ,
 `MD` double( 15, 5  )  default NULL ,
 `ME` double( 15, 5  )  default NULL ,
 `MI` double( 15, 5  )  default NULL ,
 `MN` double( 15, 5  )  default NULL ,
 `MO` double( 15, 5  )  default NULL ,
 `MS` double( 15, 5  )  default NULL ,
 `MT` double( 15, 5  )  default NULL ,
 `NC` double( 15, 5  )  default NULL ,
 `ND` double( 15, 5  )  default NULL ,
 `NE` double( 15, 5  )  default NULL ,
 `NH` double( 15, 5  )  default NULL ,
 `NJ` double( 15, 5  )  default NULL ,
 `NM` double( 15, 5  )  default NULL ,
 `NV` double( 15, 5  )  default NULL ,
 `NY` double( 15, 5  )  default NULL ,
 `OH` double( 15, 5  )  default NULL ,
 `OK` double( 15, 5  )  default NULL ,
 `OR` double( 15, 5  )  default NULL ,
 `PA` double( 15, 5  )  default NULL ,
 `RI` double( 15, 5  )  default NULL ,
 `SC` double( 15, 5  )  default NULL ,
 `SD` double( 15, 5  )  default NULL ,
 `TN` double( 15, 5  )  default NULL ,
 `TX` double( 15, 5  )  default NULL ,
 `UT` double( 15, 5  )  default NULL ,
 `VA` double( 15, 5  )  default NULL ,
 `VT` double( 15, 5  )  default NULL ,
 `WA` double( 15, 5  )  default NULL ,
 `WI` double( 15, 5  )  default NULL ,
 `WV` double( 15, 5  )  default NULL ,
 `WY` double( 15, 5  )  default NULL ,
 PRIMARY  KEY (  `ID1`  )  ) ENGINE  = InnoDB  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_backup`.`tblstatelocation` SELECT * FROM `menumine`.`tblstatelocation`;




DROP TABLE IF EXISTS `menumine_admin_backup`.`andvalues`;
 CREATE  TABLE  `menumine_admin_backup`.`andvalues` (  `id` bigint( 20  )  NOT  NULL default  '0',
 `name` varchar( 255  )  default NULL ,
 `posn` int( 11  )  NOT  NULL default  '0',
 PRIMARY  KEY (  `id` ,  `posn`  ) ,
 KEY  `id` (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`andvalues` SELECT * FROM `menumine_admin`.`andvalues`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`cannedschematic`;
 CREATE  TABLE  `menumine_admin_backup`.`cannedschematic` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `name` varchar( 100  )  default NULL ,
 `mineType` varchar( 100  )  default NULL ,
 `userName` varchar( 100  )  default NULL ,
 `groupName` varchar( 100  )  default NULL ,
 `includeBenchmark` tinyint( 1  )  default NULL ,
 `includeBenchmarkTrend` tinyint( 1  )  default NULL ,
 `includeBenchmarkGraph` tinyint( 1  )  default NULL ,
 PRIMARY  KEY (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`cannedschematic` SELECT * FROM `menumine_admin`.`cannedschematic`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`cannedschematicfields`;
 CREATE  TABLE  `menumine_admin_backup`.`cannedschematicfields` (  `id` bigint( 20  )  NOT  NULL default  '0',
 `name` varchar( 255  )  default NULL ,
 `posn` int( 11  )  NOT  NULL default  '0',
 PRIMARY  KEY (  `id` ,  `posn`  ) ,
 KEY  `id` (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`cannedschematicfields` SELECT * FROM `menumine_admin`.`cannedschematicfields`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`chainfilterparameters`;
 CREATE  TABLE  `menumine_admin_backup`.`chainfilterparameters` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 PRIMARY  KEY (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`chainfilterparameters` SELECT * FROM `menumine_admin`.`chainfilterparameters`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`fieldstodisplaybean`;
 CREATE  TABLE  `menumine_admin_backup`.`fieldstodisplaybean` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `basicProtein` tinyint( 1  )  default NULL ,
 `proteinTypeCut` tinyint( 1  )  default NULL ,
 `chickenType` tinyint( 1  )  default NULL ,
 `beefType` tinyint( 1  )  default NULL ,
 `porkType` tinyint( 1  )  default NULL ,
 `fishType` tinyint( 1  )  default NULL ,
 `seafoodType` tinyint( 1  )  default NULL ,
 `turkeyType` tinyint( 1  )  default NULL ,
 `otherProteinType` tinyint( 1  )  default NULL ,
 `shrimpType` tinyint( 1  )  default NULL ,
 `lambType` tinyint( 1  )  default NULL ,
 `proteinType` tinyint( 1  )  default NULL ,
 `cookMeth` tinyint( 1  )  default NULL ,
 `genCookMeth` tinyint( 1  )  default NULL ,
 `sauceCondDressMarMM` tinyint( 1  )  default NULL ,
 `flavEnhancSeasBrdgDesIngredMM` tinyint( 1  )  default NULL ,
 `carboVegFruit` tinyint( 1  )  default NULL ,
 `topFillIngredMM` tinyint( 1  )  default NULL ,
 `cheeseMM` tinyint( 1  )  default NULL ,
 `breadBakeGoodsMM` tinyint( 1  )  default NULL ,
 `menuItem` tinyint( 1  )  default NULL ,
 `menuItemType` tinyint( 1  )  default NULL ,
 `itemDescription` tinyint( 1  )  default NULL ,
 `cuisine` tinyint( 1  )  default NULL ,
 `cuisineFamily` tinyint( 1  )  default NULL ,
 `genMenuPart` tinyint( 1  )  default NULL ,
 `menuItemClass` tinyint( 1  )  default NULL ,
 `menuStatus` tinyint( 1  )  default NULL ,
 `price2004` tinyint( 1  )  default NULL ,
 `price2003` tinyint( 1  )  default NULL ,
 `price2002` tinyint( 1  )  default NULL ,
 `price2001` tinyint( 1  )  default NULL ,
 `price2000` tinyint( 1  )  default NULL ,
 `price1999` tinyint( 1  )  default NULL ,
 `price1998` tinyint( 1  )  default NULL ,
 `price1997` tinyint( 1  )  default NULL ,
 `price1996` tinyint( 1  )  default NULL ,
 `chain` tinyint( 1  )  default NULL ,
 `segment` tinyint( 1  )  default NULL ,
 `sector` tinyint( 1  )  default NULL ,
 `hqState` tinyint( 1  )  default NULL ,
 `price2005` tinyint( 1  )  default NULL ,
 `DayPartCategory` tinyint( 1  )  default NULL ,
 `CakeIngredient` tinyint( 1  )  default NULL ,
 `CakeUse` tinyint( 1  )  default NULL ,
 `CookieIngredient` tinyint( 1  )  default NULL ,
 `CookieUse` tinyint( 1  )  default NULL ,
 `DessertDoughCrustIngred` tinyint( 1  )  default NULL ,
 `IceCreamIngredient` tinyint( 1  )  default NULL ,
 `Syrup/Topping` tinyint( 1  )  default NULL ,
 `NutIngredient` tinyint( 1  )  default NULL ,
 `FruitorFruitFillingIngred` tinyint( 1  )  default NULL ,
 `WhippedToppingIngred` tinyint( 1  )  default NULL ,
 `CandyIngredient` tinyint( 1  )  default NULL ,
 `PrimaryFlavor` tinyint( 1  )  default NULL ,
 `TasteFlavorWords` tinyint( 1  )  default NULL ,
 `Brand` tinyint( 1  )  default NULL ,
 `VeggieFruitMM` tinyint( 1  )  default NULL ,
 `CarboMM` tinyint( 1  )  default NULL ,
 `BreadUse` tinyint( 1  )  default NULL ,
 `FlavApplication` tinyint( 1  )  default NULL ,
 `FlavorSoup` tinyint( 1  )  default NULL ,
 `SideOrAccomp` tinyint( 1  )  default NULL ,
 `HealthyTerm` tinyint( 1  )  default NULL ,
 `Cooking Sauce or Gravy` tinyint( 1  )  default NULL ,
 `Marinade` tinyint( 1  )  default NULL ,
 `Glaze` tinyint( 1  )  default NULL ,
 `Dressings` tinyint( 1  )  default NULL ,
 `DipSauceName` tinyint( 1  )  default NULL ,
 `Condiments` tinyint( 1  )  default NULL ,
 `ButterApplication` tinyint( 1  )  default NULL ,
 `SeasoningName` tinyint( 1  )  default NULL ,
 `Batter/Breading/Coating` tinyint( 1  )  default NULL ,
 `Stuff Name` tinyint( 1  )  default NULL ,
 `CheeseRollUp` tinyint( 1  )  default NULL ,
 `Cheese/CheeseSauceFillingType` tinyint( 1  )  default NULL ,
 `ProteinTopName` tinyint( 1  )  default NULL ,
 `ProteinAccompName` tinyint( 1  )  default NULL ,
 `VeggieFruitType` tinyint( 1  )  default NULL ,
 `GreenVegName` tinyint( 1  )  default NULL ,
 `VegTopName` tinyint( 1  )  default NULL ,
 `VegAccompName` tinyint( 1  )  default NULL ,
 `Fruit Type` tinyint( 1  )  default NULL ,
 `CarboType` tinyint( 1  )  default NULL ,
 `CarboTopName` tinyint( 1  )  default NULL ,
 `CarboAccompName` tinyint( 1  )  default NULL ,
 `Bread/Wrap/Chips` tinyint( 1  )  default NULL ,
 `Egg Type` tinyint( 1  )  default NULL ,
 `Hot/Cold Cereal` tinyint( 1  )  default NULL ,
 `Spread Type` tinyint( 1  )  default NULL ,
 `BreakfastPastry` tinyint( 1  )  default NULL ,
 `BreakCakeWaff` tinyint( 1  )  default NULL ,
 `LogoImageStyle` tinyint( 1  )  default NULL ,
 `BevSize` tinyint( 1  )  default NULL ,
 `ServingCount` tinyint( 1  )  default NULL ,
 `HQRegion` tinyint( 1  )  default NULL ,
 `OperatorType` tinyint( 1  )  default NULL ,
 `CountryLoc` tinyint( 1  )  default NULL ,
 `FirstYearInDatabase` tinyint( 1  )  default NULL ,
 `MasterfoodId` tinyint( 4  )  NOT  NULL default  '0',
 `ProteinFishShrimpSeafood` tinyint( 4  )  NOT  NULL default  '0',
 `keywords` bit( 1  )  default NULL ,
 `FirstYearInDatabaseSameStore` bit( 1  )  default NULL ,
 `price2006` bit( 1  )  default NULL ,
 `CuisineVerySpecific` bit( 1  )  default NULL ,
 `GrillRoastSmoke` bit( 1  )  default NULL ,
 `VegCookMeth` bit( 1  )  default NULL ,
 `CookSauceType` bit( 1  )  default NULL ,
 `DressingType` bit( 1  )  default NULL ,
 `DressingFlavor` bit( 1  )  default NULL ,
 `MexBreadType` bit( 1  )  default NULL ,
 `RoastVegItemType` bit( 1  )  default NULL ,
 `appetClassTyp` bit( 1  )  default NULL ,
 `PrepEntreeType` bit( 1  )  default NULL ,
 `BreadedFriedAppSide` bit( 1  )  default NULL ,
 `PotatoTypeUse` bit( 1  )  default NULL ,
 `SalsaType` bit( 1  )  default NULL ,
 `cookieLookAlikeDessert` bit( 1  )  default NULL ,
 `BreakfastToGo` bit( 1  )  default NULL ,
 `PizzaStyle` bit( 1  )  default NULL ,
 `BBQCook` bit( 1  )  default NULL ,
 `EthnicBreadType` bit( 1  )  default NULL ,
 `PepperType` bit( 1  )  default NULL ,
 `RiceTypeUse` bit( 1  )  default NULL ,
 `MexIngredUse` bit( 1  )  default NULL ,
 `FlavorChangeAnyYear` bit( 1  )  default NULL ,
 `NewItemBrag` bit( 1  )  default NULL ,
 `ProteinFlavorApp` bit( 1  )  default NULL ,
 `OilTypeUse` bit( 1  )  default NULL ,
 `EggItemUse` bit( 1  )  default NULL ,
 `CheeseForm` bit( 1  )  default NULL ,
 `CheeseSauceFillingType` bit( 1  )  default NULL ,
 `SoupWith` bit( 1  )  default NULL ,
 `SoupBaseBroth` bit( 1  )  default NULL ,
 `VeggieAll` bit( 1  )  default NULL ,
 `AllVegCarbFruit` bit( 1  )  default NULL ,
 `price2007` bit( 1  )  default NULL ,
 `BevMenuItem` bit( 1  )  default NULL ,
 `Side/AccompDishFlavor` bit( 1  )  default NULL ,
 `CookieType/Source` bit( 1  )  default NULL ,
 `CreamyTop` bit( 1  )  default NULL ,
 `CreamyFill` bit( 1  )  default NULL ,
 `TextureAttrib` bit( 1  )  default NULL ,
 `QualityStyle` bit( 1  )  default NULL ,
 `price2011` tinyint( 1  )  default NULL ,
 `price2010` tinyint( 1  )  default NULL ,
 `price2009` bit( 1  )  default NULL ,
 `price2008` bit( 1  )  default NULL ,
 `DairyButterCream` bit( 1  )  default NULL ,
 `TomatoType` bit( 1  )  default NULL ,
 `OnionScallionLeek` bit( 1  )  default NULL ,
 `MushroomType` bit( 1  )  default NULL ,
 PRIMARY  KEY (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`fieldstodisplaybean` SELECT * FROM `menumine_admin`.`fieldstodisplaybean`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`filterparameter`;
 CREATE  TABLE  `menumine_admin_backup`.`filterparameter` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `fieldName` varchar( 100  )  default NULL ,
 `empty` tinyint( 1  )  default NULL ,
 `mfCollectionId` bigint( 20  )  default NULL ,
 `chainCollectionId` bigint( 20  )  default NULL ,
 PRIMARY  KEY (  `id`  ) ,
 KEY  `mfCollectionId` (  `mfCollectionId`  ) ,
 KEY  `chainCollectionId` (  `chainCollectionId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`filterparameter` SELECT * FROM `menumine_admin`.`filterparameter`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`forummessage`;
 CREATE  TABLE  `menumine_admin_backup`.`forummessage` (  `ID` bigint( 20  )  NOT  NULL  auto_increment ,
 `user` varchar( 20  )  NOT  NULL default  '',
 `usergroup` varchar( 20  )  default NULL ,
 `message` mediumtext NOT  NULL ,
 `topic` varchar( 100  )  NOT  NULL default  '',
 `forumGroup` varchar( 100  )  NOT  NULL default  '',
 `date` datetime NOT  NULL default  '0000-00-00 00:00:00',
 PRIMARY  KEY (  `ID`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`forummessage` SELECT * FROM `menumine_admin`.`forummessage`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`groupmembership`;
 CREATE  TABLE  `menumine_admin_backup`.`groupmembership` (  `groupMembershipId` bigint( 20  )  NOT  NULL  auto_increment ,
 `groupMembershipGroupId` bigint( 20  )  NOT  NULL default  '0',
 `groupMembershipUserId` bigint( 20  )  NOT  NULL default  '0',
 PRIMARY  KEY (  `groupMembershipId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`groupmembership` SELECT * FROM `menumine_admin`.`groupmembership`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`groupright`;
 CREATE  TABLE  `menumine_admin_backup`.`groupright` (  `groupRightsId` bigint( 20  )  NOT  NULL  auto_increment ,
 `groupRightGroupId` bigint( 20  )  NOT  NULL default  '0',
 `groupRightsRightCode` varchar( 255  )  NOT  NULL default  '',
 PRIMARY  KEY (  `groupRightsId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`groupright` SELECT * FROM `menumine_admin`.`groupright`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`invalues`;
 CREATE  TABLE  `menumine_admin_backup`.`invalues` (  `id` bigint( 20  )  NOT  NULL default  '0',
 `name` varchar( 255  )  default NULL ,
 `posn` int( 11  )  NOT  NULL default  '0',
 PRIMARY  KEY (  `id` ,  `posn`  ) ,
 KEY  `id` (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`invalues` SELECT * FROM `menumine_admin`.`invalues`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`loginhistory`;
 CREATE  TABLE  `menumine_admin_backup`.`loginhistory` (  `lhId` bigint( 20  )  NOT  NULL  auto_increment ,
 `lhUsername` varchar( 25  )  NOT  NULL default  '',
 `lhTimestamp` datetime NOT  NULL default  '0000-00-00 00:00:00',
 `lhType` varchar( 10  )  NOT  NULL default  '',
 PRIMARY  KEY (  `lhId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`loginhistory` SELECT * FROM `menumine_admin`.`loginhistory`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`masterfoodfilterparameters`;
 CREATE  TABLE  `menumine_admin_backup`.`masterfoodfilterparameters` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `name` varchar( 100  )  default NULL ,
 `chainParamsId` bigint( 20  )  default NULL ,
 PRIMARY  KEY (  `id`  ) ,
 KEY  `chainParamsId` (  `chainParamsId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`masterfoodfilterparameters` SELECT * FROM `menumine_admin`.`masterfoodfilterparameters`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`masterfoodkeywords`;
 CREATE  TABLE  `menumine_admin_backup`.`masterfoodkeywords` (  `ID` bigint( 20  )  NOT  NULL  auto_increment ,
 `master_id` bigint( 20  )  default NULL ,
 `keywords` text,
 PRIMARY  KEY (  `ID`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`masterfoodkeywords` SELECT * FROM `menumine_admin`.`masterfoodkeywords`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`notvalues`;
 CREATE  TABLE  `menumine_admin_backup`.`notvalues` (  `id` bigint( 20  )  NOT  NULL default  '0',
 `name` varchar( 255  )  default NULL ,
 `posn` int( 11  )  NOT  NULL default  '0',
 PRIMARY  KEY (  `id` ,  `posn`  ) ,
 KEY  `id` (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`notvalues` SELECT * FROM `menumine_admin`.`notvalues`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`orvalues`;
 CREATE  TABLE  `menumine_admin_backup`.`orvalues` (  `id` bigint( 20  )  NOT  NULL default  '0',
 `name` varchar( 255  )  default NULL ,
 `posn` int( 11  )  NOT  NULL default  '0',
 PRIMARY  KEY (  `id` ,  `posn`  ) ,
 KEY  `id` (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`orvalues` SELECT * FROM `menumine_admin`.`orvalues`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`rollupelement`;
 CREATE  TABLE  `menumine_admin_backup`.`rollupelement` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `term` varchar( 255  )  default NULL ,
 `label` varchar( 255  )  default NULL ,
 `rollUpElementsId` bigint( 20  )  default NULL ,
 PRIMARY  KEY (  `id`  ) ,
 KEY  `rollUpElementsId` (  `rollUpElementsId`  ) ,
 KEY  `rollUpElementsId_63` (  `rollUpElementsId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`rollupelement` SELECT * FROM `menumine_admin`.`rollupelement`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`rollupoptions`;
 CREATE  TABLE  `menumine_admin_backup`.`rollupoptions` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `name` varchar( 100  )  default NULL ,
 `userName` varchar( 100  )  default NULL ,
 `groupName` varchar( 100  )  default NULL ,
 `permission` int( 11  )  default NULL ,
 `otherItemRollUpType` varchar( 50  )  default NULL ,
 `targetFieldName` varchar( 100  )  default NULL ,
 PRIMARY  KEY (  `id`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`rollupoptions` SELECT * FROM `menumine_admin`.`rollupoptions`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`savedquery`;
 CREATE  TABLE  `menumine_admin_backup`.`savedquery` (  `id` bigint( 20  )  NOT  NULL  auto_increment ,
 `mfParamsId` bigint( 20  )  default NULL ,
 `fieldsId` bigint( 20  )  default NULL ,
 `sqName` varchar( 100  )  default NULL ,
 `sqUserName` varchar( 100  )  default NULL ,
 `sqGroupName` varchar( 100  )  default NULL ,
 `sqPermission` int( 11  )  default NULL ,
 `mineType` varchar( 100  )  default NULL ,
 `timestamp` datetime  default NULL ,
 `sqTemplateGroup` varchar( 100  )  default NULL ,
 PRIMARY  KEY (  `id`  ) ,
 KEY  `mfParamsId` (  `mfParamsId`  ) ,
 KEY  `fieldsId` (  `fieldsId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`savedquery` SELECT * FROM `menumine_admin`.`savedquery`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`tblchain`;
 CREATE  TABLE  `menumine_admin_backup`.`tblchain` (  `ID` int( 11  )  NOT  NULL default  '0',
 `1` double  default NULL ,
 `Chain` varchar( 50  )  default NULL ,
 `HQAddress` varchar( 50  )  default NULL ,
 `HQCity` varchar( 50  )  default NULL ,
 `HQState` varchar( 50  )  default NULL ,
 `OperatorType` varchar( 50  )  default NULL ,
 `HQRegion` varchar( 50  )  default NULL ,
 `HQZip` varchar( 50  )  default NULL ,
 `Phone` varchar( 50  )  default NULL ,
 `Fax` varchar( 50  )  default NULL ,
 `WebSite` varchar( 50  )  default NULL ,
 `Units2003` int( 11  )  default NULL ,
 `Units2004` int( 11  )  default NULL ,
 `Sales2003` double  default NULL ,
 `Sales2004` double  default NULL ,
 `ParentCo` varchar( 50  )  default NULL ,
 `ParentAddress` varchar( 50  )  default NULL ,
 `ParentCity` varchar( 50  )  default NULL ,
 `ParentState` varchar( 50  )  default NULL ,
 `ParentZip` int( 11  )  default NULL ,
 `Segment` varchar( 50  )  default NULL ,
 `SectorName` varchar( 50  )  default NULL ,
 `NatRegLocal` varchar( 50  )  default NULL ,
 `PerStoreAver` double  default NULL ,
 `MAP-Chains` varchar( 50  )  default NULL ,
 `CountryLoc` varchar( 50  )  default NULL ,
 `FirstYearInDatabase` int( 11  )  default NULL ,
 `IndusRankDoll-04` varchar( 50  )  default NULL ,
 `IndusRankDoll-03` varchar( 50  )  default NULL ,
 `IndusRankUnits-04` varchar( 50  )  default NULL ,
 `IndusRankUnits-03` varchar( 50  )  default NULL ,
 `SegRankDoll-04` varchar( 50  )  default NULL ,
 `SegRankDoll-03` varchar( 50  )  default NULL ,
 `SegRankUnits-04` varchar( 50  )  default NULL ,
 `SegRankUnits-03` varchar( 50  )  default NULL ,
 PRIMARY  KEY (  `ID`  ) ,
 KEY  `FK101A3DC3A2799791` (  `Chain`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`tblchain` SELECT * FROM `menumine_admin`.`tblchain`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`tblchainstat`;
 CREATE  TABLE  `menumine_admin_backup`.`tblchainstat` (  `1` double  default NULL ,
 `Chain` varchar( 50  )  default NULL ,
 `HQAddress` varchar( 50  )  default NULL ,
 `HQCity` varchar( 50  )  default NULL ,
 `HQState` varchar( 50  )  default NULL ,
 `HQZip` varchar( 50  )  default NULL ,
 `Phone` varchar( 50  )  default NULL ,
 `Fax` varchar( 50  )  default NULL ,
 `WebSite` varchar( 50  )  default NULL ,
 `Units2003` int( 11  )  default NULL ,
 `Units2004` int( 11  )  default NULL ,
 `Sales2003` double  default NULL ,
 `Sales2004` double  default NULL ,
 `IndusRankDoll-04` varchar( 50  )  default NULL ,
 `IndusRankDoll-03` varchar( 50  )  default NULL ,
 `IndusRankUnits-04` varchar( 50  )  default NULL ,
 `IndusRankUnits-03` varchar( 50  )  default NULL ,
 `SegRankDoll-04` varchar( 50  )  default NULL ,
 `SegRankDoll-03` varchar( 50  )  default NULL ,
 `SegRankUnits-04` varchar( 50  )  default NULL ,
 `SegRankUnits-03` varchar( 50  )  default NULL ,
 `ParentCo` varchar( 50  )  default NULL ,
 `ParentAddress` varchar( 50  )  default NULL ,
 `ParentCity` varchar( 50  )  default NULL ,
 `ParentState` varchar( 50  )  default NULL ,
 `ParentZip` int( 11  )  default NULL ,
 `Segment` varchar( 50  )  default NULL ,
 `SectorName` varchar( 50  )  default NULL ,
 `NatRegLocal` varchar( 50  )  default NULL ,
 `PerStoreAver` double  default NULL ,
 `MAP-Chains` varchar( 50  )  default NULL ,
 `ID` int( 11  )  default NULL  ) ENGINE  = InnoDB  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`tblchainstat` SELECT * FROM `menumine_admin`.`tblchainstat`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`tblstatelocation`;
 CREATE  TABLE  `menumine_admin_backup`.`tblstatelocation` (  `ID1` int( 11  )  NOT  NULL default  '0',
 `IDnumber` double  default NULL ,
 `1` double  default NULL ,
 `Chain` varchar( 255  )  default NULL ,
 `AK` double  default NULL ,
 `AL` double  default NULL ,
 `AR` double  default NULL ,
 `AZ` double  default NULL ,
 `CA` double  default NULL ,
 `CO` double  default NULL ,
 `CT` double  default NULL ,
 `DC` double  default NULL ,
 `DE` double  default NULL ,
 `FL` double  default NULL ,
 `GA` double  default NULL ,
 `HI` double  default NULL ,
 `IA` double  default NULL ,
 `ID` double  default NULL ,
 `IL` double  default NULL ,
 `IN` double  default NULL ,
 `KS` double  default NULL ,
 `KY` double  default NULL ,
 `LA` double  default NULL ,
 `MA` double  default NULL ,
 `MD` double  default NULL ,
 `ME` double  default NULL ,
 `MI` double  default NULL ,
 `MN` double  default NULL ,
 `MO` double  default NULL ,
 `MS` double  default NULL ,
 `MT` double  default NULL ,
 `NC` double  default NULL ,
 `ND` double  default NULL ,
 `NE` double  default NULL ,
 `NH` double  default NULL ,
 `NJ` double  default NULL ,
 `NM` double  default NULL ,
 `NV` double  default NULL ,
 `NY` double  default NULL ,
 `OH` double  default NULL ,
 `OK` double  default NULL ,
 `OR` double  default NULL ,
 `PA` double  default NULL ,
 `RI` double  default NULL ,
 `SC` double  default NULL ,
 `SD` double  default NULL ,
 `TN` double  default NULL ,
 `TX` double  default NULL ,
 `UT` double  default NULL ,
 `VA` double  default NULL ,
 `VT` double  default NULL ,
 `WA` double  default NULL ,
 `WI` double  default NULL ,
 `WV` double  default NULL ,
 `WY` double  default NULL ,
 PRIMARY  KEY (  `ID1`  )  ) ENGINE  = InnoDB  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`tblstatelocation` SELECT * FROM `menumine_admin`.`tblstatelocation`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`tblstatesbyregion`;
 CREATE  TABLE  `menumine_admin_backup`.`tblstatesbyregion` (  `ID` int( 11  )  NOT  NULL default  '0',
 `State` varchar( 255  )  default NULL ,
 `Region` varchar( 255  )  default NULL ,
 PRIMARY  KEY (  `ID`  )  ) ENGINE  = InnoDB  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`tblstatesbyregion` SELECT * FROM `menumine_admin`.`tblstatesbyregion`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`user`;
 CREATE  TABLE  `menumine_admin_backup`.`user` (  `userId` bigint( 20  )  NOT  NULL  auto_increment ,
 `userUserName` varchar( 20  )  NOT  NULL default  '',
 `userPassword` varchar( 20  )  NOT  NULL default  '',
 `userEmail` varchar( 100  )  NOT  NULL default  '',
 `userInactive` tinyint( 1  )  default NULL ,
 `userRole` varchar( 20  )  NOT  NULL default  '',
 `userExpirationDate` datetime  default NULL ,
 `userFirstName` varchar( 50  )  default NULL ,
 `userLastName` varchar( 50  )  default NULL ,
 `userComments` mediumtext,
 `userCompany` varchar( 50  )  default NULL ,
 `userStreet1` varchar( 50  )  default NULL ,
 `userStreet2` varchar( 50  )  default NULL ,
 `userCity` varchar( 50  )  default NULL ,
 `userState` varchar( 50  )  default NULL ,
 `userZip` varchar( 50  )  default NULL ,
 `userPhone` varchar( 50  )  default NULL ,
 PRIMARY  KEY (  `userId`  ) ,
 UNIQUE  KEY  `userEmail` (  `userEmail`  ) ,
 UNIQUE  KEY  `userUserName` (  `userUserName`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`user` SELECT * FROM `menumine_admin`.`user`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`usergroup`;
 CREATE  TABLE  `menumine_admin_backup`.`usergroup` (  `groupId` bigint( 20  )  NOT  NULL  auto_increment ,
 `groupName` varchar( 25  )  NOT  NULL default  '',
 PRIMARY  KEY (  `groupId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`usergroup` SELECT * FROM `menumine_admin`.`usergroup`;
DROP TABLE IF EXISTS `menumine_admin_backup`.`userpref`;
 CREATE  TABLE  `menumine_admin_backup`.`userpref` (  `prefId` bigint( 20  )  NOT  NULL  auto_increment ,
 `prefUserName` varchar( 20  )  NOT  NULL ,
 `prefKey` varchar( 50  )  NOT  NULL ,
 `prefValue` varchar( 255  )  default NULL ,
 PRIMARY  KEY (  `prefId`  )  ) ENGINE  =  MyISAM  DEFAULT CHARSET  = latin1;

INSERT INTO `menumine_admin_backup`.`userpref` SELECT * FROM `menumine_admin`.`userpref`;
